google/s2a-go

WORKSPACE
s2a.go
tools/internal_ci/run_tests.sh

Update Bazel dependencies, which also fixes the broken Kokoro tests.

Update Bazel dependencies to newer versions.

---

go.mod

While working on TLS Configuration Store library implementation, I ran into an error : 
"go:embed requires go1.16 or later (-lang was set to go1.14; check go.mod)".  Update go.mod to support go:embed.

Update go.mod to 1.16 to support go:embed

---

internal/v2/fakes2av2/fakes2av2_test.go

Instead of starting up / stopping the service per unit test, set it up once before the for loop, and use it for all the tests.

Improve fakes2av2 test suite

---

internal/v2/tls_config_store/tls_config_store.go
internal/v2/tls_config_store/tls_config_store_test.go

Remove InsecureSkipVerify from server TLS config.
As noted in the [documentation for InsecureSkipVerify](https://cs.opensource.google/go/go/+/refs/tags/go1.18.3:src/crypto/tls/common.go;l=647), this field is only used if set in the client TLS config. It controls whether a client verifies the server's certificate chain and host name.
Brought up Go echo client server to verify this change does not impact anything:
bazel run fakes2av2_server
bazel run server
bazel run client

Remove InsecureSkipVerify from server TLS config

---

internal/v2/BUILD
internal/v2/s2av2_e2e_test.go

Update existing automated end to end integration tests to use S2Av2 client. Note that PR#37 has to merge, then we need to rebase this PR to pick up those changes, then I can test the changes in this PR. We can technically do all this before merging #37, but then we won't be able to test our implementation of remote signer.

Add end to end integration tests to use S2Av2 client

---

internal/v2/cert_verifier/BUILD
internal/v2/cert_verifier/cert_verifier.go
internal/v2/cert_verifier/cert_verifier_test.go
internal/v2/fakes2av2/fakes2av2.go
internal/v2/fakes2av2/fakes2av2_test.go

Modify fake s2av2 to return InvalidArgument status when error is triggered by bad data given by s2av2 client in SessionReq. In this case, RPC does not return an error, rather it builds a SessionResp indicating bad data given by client in SessionReq. Added unit test to test this new branch of code. 
Handle SessionResp Status field in Cert Verifier lib.

Handle SessionResp Status field in Cert Verifier

---

internal/v2/BUILD
internal/v2/cert_verifier/BUILD
internal/v2/cert_verifier/cert_verifier.go
internal/v2/cert_verifier/cert_verifier_test.go
internal/v2/remote_signer/BUILD
internal/v2/remote_signer/remote_signer.go
internal/v2/remote_signer/remote_signer_test.go
internal/v2/s2av2.go
internal/v2/s2av2_e2e_test.go
internal/v2/s2av2_test.go
internal/v2/tls_config_store/BUILD
internal/v2/tls_config_store/tls_config_store.go
internal/v2/tls_config_store/tls_config_store_test.go

Modify s2av2 to call tokenmanager library to establish a default token that can be attached to all RPCs made to s2av2. 
Note that in actual s2av2 implementation the only time the token is read is when the first SessionReq is made, all following SessionReq RPC authentication mechanisms are not read.

Call the token manager for authentication mechanism

---

internal/v2/fakes2av2/BUILD
internal/v2/fakes2av2/fakes2av2.go
internal/v2/fakes2av2/fakes2av2_test.go
internal/v2/remote_signer/BUILD
internal/v2/remote_signer/remote_signer.go
internal/v2/remote_signer/remote_signer_test.go

Modify fake s2av2 to return InvalidArgument status when error is triggered by bad data given by s2av2 client in SessionReq. In this case, RPC does not return an error, rather it builds a SessionResp indicating bad data given by client in SessionReq. Added unit test to test this new branch of code.
Handle SessionResp Status field in Remote Signer lib.

Handle SessionResp Status field in Remote Signer

---

internal/v2/remote_signer/remote_signer.go
internal/v2/tls_config_store/tls_config_store.go
internal/v2/tls_config_store/tls_config_store_test.go

Add GetConfigForClient field to Server TLS Config. 
This allows the Server to use SNI from ClientHello to return a config with the certificate that the client expects, and establish a secure connection. 
Added corresponding unit tests to TLS Config store test suite. While adding these tests, cleaned up existing tests to ensure stream creation happens during each unit tests(in future if we add failing tests, stream needs to be recreated; it cannot be reused by failing / passing tests)

Add GetConfigForClient field to Server TLS Config

---

internal/v2/cert_verifier/cert_verifier.go
internal/v2/cert_verifier/cert_verifier_test.go
internal/v2/fakes2av2/fakes2av2.go
internal/v2/fakes2av2/fakes2av2_test.go

Add an if statement to check ValidationResult in the ValidatePeerCertificateChainResp SessionResp returned by S2Av2. 
The Fake S2Av2 Service layer was already populating and testing ValidationResult and ValidationDetails in fakes2av2.go and fakes2av2_test.go.
Also, fix some typos in VerifyServerCertificateChain error messages.

Check ValidationResult

---

WORKSPACE
go.mod
go.sum
internal/handshaker/service/BUILD
internal/handshaker/service/service.go

The default gRPC dialer does not seem to work on AppEngine. This will be e2e tested by deploying a Go app to AppEngine.

Add support for AppEngine-specific dialer.

---

internal/v2/s2av2.go
internal/v2/s2av2_e2e_test.go
s2a.go

during handshake, s2a will check if the hostname found in server's certificate matches the expected server name. Currently s2a does not allow specifying this expected server name and using an empty string, which leads to error in handshake.
this PR makes it possible to specify such server name when building a client tls config instance.
bazel test ...
bazel build ...

add an option to pass server name into s2a's tls config

---

internal/v2/s2av2.go
internal/v2/s2av2_test.go
s2a.go
s2a_test.go

grpc's underlying http2 client expects the security protocol to be 'tls', so it will talk https, otherwise default is http.

fix: return tls as the security protocol

---

s2a_options.go

this is step one to make v2 the default and deprecate the `EnableV2` flag

add EnableLegacyMode to s2a_options

---

BUILD
fallback/BUILD
internal/v2/BUILD

https://github.com/google/s2a-go/issues/99
When bazel auto-generates BUILD files for non-bazel module, e.g. google-api-go-client, for  the `deps` list, the conventions is to use the last section of an importPath as its target.  So for import `github.com/google/s2a-go`, the auto-generated build dependency is:  '@com_github_google_s2a_go//:s2a-go'.  However our actual go_library target is `s2a`, not `s2a-go`. This PR creates an alias to bridge this difference.
- Also fixed a similar issue for the fallback target.
- fix the s2a visiblity, make it public

fix build target naming and visibility

---

s2a_options.go

This is needed to allow user to configure the server authorization policy and the stream to talk to the S2A server.

Add option to inject custom bidirectional stream to S2A.

---

internal/v2/s2av2.go
internal/v2/s2av2_e2e_test.go
internal/v2/s2av2_test.go
s2a.go
s2a_options.go
stream/s2a_stream.go

Moved the declaration of `S2AStream` into inner packages to avoid circular dependency.

Pass options that allow injection of custom stream to internal v2 code.

---

internal/v2/s2av2.go
internal/v2/s2av2_e2e_test.go
retry/retry.go
retry/retry_test.go
s2a.go
s2a_e2e_test.go

add retry logic similar to the code used for talking to metadata server:
https://github.com/googleapis/google-cloud-go/blob/main/compute/metadata/retry.go
summary: err will be retried for up to 5 times: 
1st backoff:   random duration up to 0.1s
2nd backoff: random duration up to 0.2s
3rd backoff:  random duration up to 0.4s
4th backoff:  random duration up to 0.8s
5th backoff:  random duration up to 1.6s
tested running a test gae app and triggering the retry logic by:
case1: giving it a wrong s2a address
case2: setting a wrong server name in tls.config, so the handshake fails
and was able to observe (via log) 5 retries made for both cases.

retry if err when talking to s2a gRPC server

---

internal/v2/s2av2.go
s2a.go

- for HTTP, create a new tls config (new stream to S2A) for each DialContext retry
- for GRPC, remove the retry on calls to creds.ServerHandshake and creds.ClientHandshake. It makes more sense to let the current handshake fail, and rely on re-connect.

update retry logic

---

s2a_options.go

So that these constants will have type `VerificationMode` instead of just `int`.

Update enum consts to take the corresponding type

---

internal/record/record.go

break is not needed. When case is empty, we exit the switch without executing the default.

Remove break
